// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GherkinSync
{
    internal sealed partial class Vsix
    {
        public const string Id = "GherkinSync.cf821808-8c80-44bf-b6c3-b34bd94ec5f8";
        public const string Name = "GherkinSync";
        public const string Description = @"A tool to synchronize Gherkin Test Scenarios with Azure DevOps test cases.";
        public const string Language = "en-US";
        public const string Version = "1.1.0";
        public const string Author = "Cipriano Oliveira";
        public const string Tags = "Gherkin, Test Case, Sync";
        public const bool IsPreview = true;
    }
}
